add namespace model and methods
exonlv/rpc pull request #5
Opened 2017-01-13 17:32 UTC by SerjAntiquity

2017-01-14 12:06 UTC, cloudedcat requested changes

2017-01-14 12:06 UTC, cloudedcat commented on models/namespace/sql.go
> +func (_ *Namespace) Add(ns Namespace, ok *bool) {
Каждый метод из пункта Методы, должен быть написан по требованиям пакета RPC. Аналогично для ост. методов

2017-01-14 12:06 UTC, cloudedcat commented on models/namespace/namespace.go
> +	ID        int64
тип string, т.к. в postgres атрибут должен иметь тип uuid, аналогично для других атрибутов, которые в pg имею тип uuid

2017-01-14 12:06 UTC, cloudedcat commented on models/namespace/namespace.sql
> +  id serial NOT NULL,
тип uuid. См. обновленный пример

2017-01-14 12:06 UTC, cloudedcat commented on models/namespace/namespace.sql
> +  user_id integer NOT NULL references users(user_id),
В тз user_id имеет тип uuid(пример с users исправлен)

2017-01-17 13:11 UTC, cloudedcat requested changes

2017-01-17 13:11 UTC, cloudedcat commented on models/namespace/sql.go
> +	_, err := db.Exec("UPDATE namespaces SET removed=TRUE where id=$1", ns.ID)
Update не выдаст ошибку если нечего обновлять(Допустим, пытаемся обновить несуществующий ). Аналогично для всех update запросов. Можно использовать result.RowsAffected()

2017-01-17 13:11 UTC, cloudedcat commented on models/namespace/sql.go
> +func (_ *Namespace) GetAll(userId string, resp []*Namespace) error {
GetAll (user_id string, *[]Namespace). Указатель на массив, не массив указателей

2017-01-17 13:11 UTC, cloudedcat commented on models/namespace/sql.go
> +	resp = namespaces
Необходимо менять память, на которую указывает указатель, а не заменять указатель на другой(в этом нет никакого смысла)

2017-01-17 13:11 UTC, cloudedcat commented on models/namespace/sql.go
> +	resp = ns
Аналогично

2017-01-17 23:00 UTC, SerjAntiquity commented
немного поправил код, как мне кажется - так удобнее. Актуальны эти 2 коммита  [1](https://github.com/exonlv/rpc/pull/5/commits/0d147a34be922eac8c1a8aa27b0f3999ee052271)
[2](https://github.com/exonlv/rpc/pull/5/commits/911ff62c181a7179f22357c398e03f06a6880ad7)

2017-01-18 10:15 UTC, merged